### ISSUE TITLE
iPad support

### ISSUE THREAD

**Issue by megastep** [domesticcatsoftware/DCIntrospect#11]
I am working on a universal iPhone/iPad app and DCIntrospect is great for debugging and tweaking on the iPhone side of things, however it seems to completely not work so far on the iPad side. I haven't exactly looked too closely at what might be triggering this, but it would be great to have full iPad support.

**Comment by domesticcatsoftware** [comment]
All seems to be working OK over here.  Are you able to send me an example project I can take a look at?

**Comment by megastep** [comment]
I can't really give you access to the project I am working on right but I'll see if I can build a test case.

**Comment by megastep** [comment]
Part of the problem might actually be related to Xcode 4.2 and the iOS 5 beta, I should add. I still had issues on the current SDK, but it seems to be worse with the new version...

**Comment by megastep** [comment]
OK, it seems I have narrowed down the problem to the fact that the status bar is being hidden in my project. If it is shown, then it works OK, but if it is hidden then all hell breaks loose. This case should probably be handled properly since there are quite a few apps that require the status bar to be hidden.

I have put together a test project that you can check out to see the problem. You can just comment the line in the app delegate that removes the status bar to make it work again.

http://www.megastep.org/github/DCIntrospectPadTest.zip

**Comment by megastep** [comment]
I also have a simple one-liner to fix this issue! The sharedIntrospector class method should just have this line instead to hide the status bar overlay when the status bar is hidden:

```
    sharedInstance.showStatusBarOverlay = ![UIApplication sharedApplication].statusBarHidden;
```

This makes DCIntrospector work in my iPad project, which will be very helpful. :)

**Comment by domesticcatsoftware** [comment]
Thanks, that's awesome!  Been trying to work out the problem with this for a while.  I couldn't replicate it, now I understand why.  Makes sense now.
