### ISSUE TITLE
Feature Request: Enter GDB

### ISSUE THREAD

**Issue by soffes** [domesticcatsoftware/DCIntrospect#2]
I'm not really sure if this is possible, but it would be amazing if there was a key to break and enter gdb so you could adjust stuff like background color and such or do other tweaking.

**Comment by jakemarsh** [comment]
This might be easily accomplished using something like Timac's BreakIntoGDB() function described (and full source code for is) here: http://blog.timac.org/?p=190

**Comment by domesticcatsoftware** [comment]
I have this working on a local branch - it's not all that pretty but reasonably functional.  Basically it drops you into GDB with a reference to the UIView you have currently selected, and you can then manipulate it by sending commands from there.  Is that what you're after?

**Comment by soffes** [comment]
Ya that sounds perfect :)

**Comment by domesticcatsoftware** [comment]
Done :)
