### ISSUE TITLE
Change Readme

### ISSUE THREAD

**Issue by steipete** [domesticcatsoftware/DCIntrospect#24]
TARGET_IPHONE_SIMULATOR is defined on the device, but set to _false_.

So instead of
# ifdef TARGET_IPHONE_SIMULATOR

```
[[DCIntrospect sharedIntrospector] start];
```
# endif

correct is:
# if TARGET_IPHONE_SIMULATOR

```
[[DCIntrospect sharedIntrospector] start];
```
# endif

**Comment by mackuba** [comment]
+1, I've just found that the reason why the iPhone keyboard acts weird in some cases on the device is that DCIntrospect is active when it shouldn't :)

**Comment by guoxj** [comment]
+1 yes ,the keyboard acts weird.

**Comment by domesticcatsoftware** [comment]
This is now fixed on the main branch.  Pretty silly mistake to make really!
