### ISSUE TITLE
Feature Request: Accessibility Info

### ISSUE THREAD

**Issue by soffes** [domesticcatsoftware/DCIntrospect#3]
It would be great to in one of the log options (or perhaps a new one) to log the accessibility info. This would make writing automated view tests much easier.

**Comment by alaborie** [comment]
I agree this feature is missing.

**Comment by domesticcatsoftware** [comment]
I've addressed this with the shortcut 'a', but it's not ideal as the Accessibility Inspector needs to be on for it to work.  I've tried @0xced's solution with not much luck (https://twitter.com/#!/0xced/statuses/29560131594) — only the frame get's reported.
