### ISSUE TITLE
inputTextView captures all shake events

### ISSUE THREAD

**Issue by kevboh** [domesticcatsoftware/DCIntrospect#40]
Shake events don't propagate past the inputTextView to the rest of the application. To reproduce, implement a simple project with shake to undo support (like https://github.com/dcgrigsby/TallyTrucks), add DCIntrospect, then run and try to shake-to-undo in the simulator (Hardware -> Shake Gesture or ^⌘Z). Undo will not prompt.

**Comment by domesticcatsoftware** [comment]
Can’t really think of a workaround to this right now, I’d suggest using a gesture recogniser to invoke it rather than the keyboard, then turn off key bindings so the text field doesn't interfere with the responder chain.
