### ISSUE TITLE
ARC 

### ISSUE THREAD

**Issue by Tintenklecks** [domesticcatsoftware/DCIntrospect#44]
... this would have been exactly what I was looking for ... but all my projects are with ARC :-(
Do you plan to make the modification?

**Comment by AlexEscalante** [comment]
It would be nice to have DCIntrospect working with ARC. Maybe I can lend a hand, not sure... The first problem I saw was trying to cast a malloc()ed block into Class*. Not sure how to proceed with this, but maybe I can get some time later.

**Comment by lukaswelte** [comment]
I've made this modification 
You can find it here http://www.lukaswelte.de/?p=66 under Link zum Repository

**Comment by domesticcatsoftware** [comment]
I will be updating the project to ARC at some stage, but for now just disable ARC on the DCIntrospect files using the build flag -fno-objc-arc: http://stackoverflow.com/questions/6646052/how-can-i-disable-arc-for-a-single-file-in-a-project
