### ISSUE TITLE
Provide ability to select a superview

### ISSUE THREAD

**Issue by cbess** [domesticcatsoftware/DCIntrospect#47]
Provide a keyboard action that will select the superview of the currently selected view.

**Comment by gradha** [comment]
Isn't that already implemented? The readme is not complete, run the demo and press ? to get more key information.

**Comment by cbess** [comment]
I didn't see it. I saw, "center in superview."

**Comment by gradha** [comment]
Search kDCIntrospectKeysMoveUpInViewHierarchy in DCIntrospectSettings.h.

**Comment by cbess** [comment]
Ah, thanks! I didn't realize that selects the view as well.
